### ISSUE TITLE
CORS Policy

### ISSUE THREAD

**Issue by mrwunderbar666** [opted-eu/meteor-dev#41]
Front-end clients require a more flexible CORS policy

**Comment by iwellaway** [comment]
I'm getting the CORS error again when trying to access the user/login endpoint. Is this a different CORS config to the public-facing endpoints?

**Comment by iwellaway** [comment]
Tagging @mrwunderbar666

**Comment by mrwunderbar666** [comment]
> Tagging @mrwunderbar666

Oh dear!

Could you paste the error message and request headers here please?

**Comment by iwellaway** [comment]
![image](https://github.com/opted-eu/meteor-dev/assets/1670728/79450c8e-b6d7-4a74-8004-ad939894c9fd)

async function loginUser(credentials) {
    console.log(JSON.stringify(credentials))
    return fetch('https://meteor.balluff.dev/api/user/login', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(credentials)
    })
        .then(data => data.json())

}

//credentials = {"username":"iwellaway@hotmail.com","password":"******"}

**Comment by iwellaway** [comment]
![image](https://github.com/opted-eu/meteor-dev/assets/1670728/01211b3e-92bf-48d8-a478-99ac8331995a)

async function loginUser(credentials) {
    console.log(JSON.stringify(credentials))
    return fetch('https://meteor.balluff.dev/api/user/login', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(credentials)
    })
        .then(data => data.json())

}

//credentials = {"username":"iwellaway@hotmail.com","password":"******"}

**Comment by iwellaway** [comment]
![image](https://github.com/opted-eu/meteor-dev/assets/1670728/2042ac91-308c-4c07-94cb-6f06937e1ee2)

**Comment by mrwunderbar666** [comment]
there is indeed a problem, your request should return 400 with proper CORS headers (see issue #54). You need to supply the correct JSON keys, then it works:

```
const credentials = {"email": "contributor@opted.eu", "password": "contributor123"}
```

**Comment by mrwunderbar666** [comment]
closing this for now. Reopen if issue pops up again
