### ISSUE TITLE
API: Users cannot change their passwords

### ISSUE THREAD

**Issue by mrwunderbar666** [opted-eu/meteor-dev#55]
thanks @iwellaway for reporting this

**Comment by mrwunderbar666** [comment]
thanks!
you should now get a 401 error, in case the old password doesn't match, or the new password has a problem

**Comment by iwellaway** [comment]
Thanks Paul, all working now.

Ian

From: mrwunderbar666 ***@***.***>
Date: Wednesday, 29 November 2023 at 07:08
To: opted-eu/meteor-dev ***@***.***>
Cc: Wellaway, Ian ***@***.***>, Mention ***@***.***>
Subject: Re: [opted-eu/meteor-dev] API: Users cannot change their passwords (Issue #55)
CAUTION: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.


thanks!
you should now get a 401 error, in case the old password doesn't match, or the new password has a problem
